version: '3.8'

services:

  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_DB: appdb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - appnet

  php:
    build: ./backend
    container_name: php
    ports:
      - "8080:80"
    depends_on:
      - postgres
    volumes:
      - ./backend:/var/www/html
    networks:
      - appnet

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: sh -c "npm install && npm run dev -- --host"
    networks:
      - appnet

  python-api:
    build: ./api
    container_name: python-api
    ports:
      - "8000:8000"
    volumes:
      - ./api:/app
    networks:
      - appnet

volumes:
  pgdata:

networks:
  appnet: